// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4f-q0qPu9lSmVsrKdcAdflABRYe04R8o',
    appId: '1:338867520995:web:a4a9cfb00bc036eb2b0cd6',
    messagingSenderId: '338867520995',
    projectId: 'clasificadora-93348',
    authDomain: 'clasificadora-93348.firebaseapp.com',
    databaseURL: 'https://clasificadora-93348-default-rtdb.firebaseio.com',
    storageBucket: 'clasificadora-93348.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8UhJiwW82IJg6yO2NBs4J4R1F9FgL_JI',
    appId: '1:338867520995:android:fca1172507539c512b0cd6',
    messagingSenderId: '338867520995',
    projectId: 'clasificadora-93348',
    databaseURL: 'https://clasificadora-93348-default-rtdb.firebaseio.com',
    storageBucket: 'clasificadora-93348.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3iWfoQK_X2xKHWFMnqlavc3koVcSWBjA',
    appId: '1:338867520995:ios:0c100f3e98ea1ba92b0cd6',
    messagingSenderId: '338867520995',
    projectId: 'clasificadora-93348',
    databaseURL: 'https://clasificadora-93348-default-rtdb.firebaseio.com',
    storageBucket: 'clasificadora-93348.appspot.com',
    iosClientId: '338867520995-hmk9gt4pro2td4tprrupkqobiommcpvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.appWebTesis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3iWfoQK_X2xKHWFMnqlavc3koVcSWBjA',
    appId: '1:338867520995:ios:11c864fc8be24eae2b0cd6',
    messagingSenderId: '338867520995',
    projectId: 'clasificadora-93348',
    databaseURL: 'https://clasificadora-93348-default-rtdb.firebaseio.com',
    storageBucket: 'clasificadora-93348.appspot.com',
    iosClientId: '338867520995-j4jjmhmblv7l0ht6f0dkochat14hmqg2.apps.googleusercontent.com',
    iosBundleId: 'com.example.appWebTesis.RunnerTests',
  );
}
